#!/bin/bash

#SBATCH --ntasks-per-node=10 # Tasks per node
#SBATCH --nodes=1 #number of nodes requested
#SBATCH --mem-per-cpu=90GB
#SBATCH --time=4-00:00:00
#SBATCH --partition=ngcm

module load python/3.6.4
module load numpy/1.14.0
module load matplotlib/2.1.2
module load pandas
module load scipy



cd abides/
python parallel.py -c baseline -b T -d 20210325 -l btc20210312 -np 10 -ns 50 -st 09:00:00 -et 16:00:00 -n 45000
